### ISSUE TITLE
node server.js error on install

### ISSUE THREAD

**Issue by mrneilypops** [unwitting/voolt#37]
`mrneilypops@ubuntu-fra1-01:/var/www/voolt$ npm start --production

> voolt@1.15.6 start /var/www/voolt
> node server.js

/var/www/voolt/server.js:65
  for (let key in extraData) {
       ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

npm ERR! Linux 4.4.0-43-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start" "--production"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! voolt@1.15.6 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the voolt@1.15.6 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the voolt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs voolt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls voolt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/voolt/npm-debug.log
`

Digital Ocean droplet
ubuntu-fra1-01 2 GB Memory / 20 GB Disk / FRA1 - Ubuntu 16.04.1 x64
Mongodb installed and running as per;
https://www.digitalocean.com/community/tutorials/how-to-install-mongodb-on-ubuntu-16-04

**Comment by unwitting** [comment]
Hi @mrneilypops! Looks to me like you might be using too early a version of Node - you need Node v6.x to run voolt :) What does `node -v` output?

**Comment by unwitting** [comment]
If you don't have node v6.x on your droplet, I recommend using (or [getting](https://github.com/creationix/nvm#install-script) then using) NVM (node version manager).

With that, you can just run `nvm install 6` to get node 6.x :)

**Comment by mrneilypops** [comment]
`mrneilypops@ubuntu-fra1-01:/var/www/voolt$ node -v
v4.2.6`
I will try and install NVM...

**Comment by mrneilypops** [comment]
NVM installed and running voolt...
http://46.101.111.169:8000/all

**Comment by mrneilypops** [comment]
Hi Jack,

Up and running after installing NVM...

http://46.101.111.169:8000/all

Just got to get a server running with a sexy domain name.

Thanks for the help and I also like your Ghost theme8-)


Cheers,

Neil

**Comment by unwitting** [comment]
Brilliant! As I said on email, let me know if you hit anything with the app. Could be that I accidentally branded it too much with 'voolt' when you may want to use your own naming all over etc.

**Comment by unwitting** [comment]
@mrneilypops I also recommend you follow this repo since I make semi-hefty changes to voolt on a frequent basis: for example, I just fixed it up with a GOOGLE_ANALYTICS_ID config so that you can make use of your own analytics, or none at all.
