### ISSUE TITLE
Glitchy layout in chrome

### ISSUE THREAD

**Issue by craigiw** [unwitting/voolt#39]
Image viewing page constantly resizes in Chrome 54. Seems to be caused by the ms counter top left of the page.  Bottom of image is also impossible to view.

**Comment by unwitting** [comment]
Thanks for reporting - would you be able to confirm your browser resolution if you know it?

**Comment by unwitting** [comment]
I ask because I'm using Chrome 54 too and don't have problems!

**Comment by craigiw** [comment]
524x1093 according to http://www.webpagefx.com/tools/whats-my-browser-size/

Chrome 53.0.2785.154 (64-bit) on ChromeOS.

**Comment by craigiw** [comment]
Yeah sorry it's actually 53.

**Comment by craigiw** [comment]
It doesn't happen with every picture, but maybe 25% of them.

Here is video of it happening https://app.hyfy.io/v/abYXe3Yhrk/

**Comment by unwitting** [comment]
Aaah - looks like you're _just_ on the cusp of the overflow, so the numbers sometimes push it and sometimes don't onto two rows. And it happens with some but not others because some are just old enough :) Will look into it

**Comment by unwitting** [comment]
Completely out of my own interest, what device is that? Unusual aspect ratio!

**Comment by craigiw** [comment]
14 inch HP Chromebook.  Settings say the resolution is 1366 x 768.

**Comment by unwitting** [comment]
You should be good to go? Reopen if not :)

**Comment by craigiw** [comment]
Yep works fine now :)
